// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter } from "./tables/Counter.sol";
import { ERC20Balance } from "./tables/ERC20Balance.sol";
import { ERC20Allowance } from "./tables/ERC20Allowance.sol";
import { MoaiAttributeTable, MoaiAttributeTableTableId } from "./tables/MoaiAttributeTable.sol";
import { ERC721BalanceTable } from "./tables/ERC721BalanceTable.sol";
import { ERC721OwnerTable } from "./tables/ERC721OwnerTable.sol";
import { ERC721AprovalAllTable } from "./tables/ERC721AprovalAllTable.sol";
import { ElementConfigTable, ElementConfigTableData, ElementConfigTableTableId } from "./tables/ElementConfigTable.sol";
import { LandClaimTable, LandClaimTableData, LandClaimTableTableId } from "./tables/LandClaimTable.sol";
import { TokenClaimTable, TokenClaimTableTableId } from "./tables/TokenClaimTable.sol";
import { CellsOwnerTable } from "./tables/CellsOwnerTable.sol";
import { CellsTable, CellsTableData, CellsTableTableId } from "./tables/CellsTable.sol";
import { CellEventTable, CellEventTableData, CellEventTableTableId } from "./tables/CellEventTable.sol";
