// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IInitialConfigSystem {
  function initialElement() external;

  function initialMoaiAttribute(uint256 nftId, uint8 elementType) external;
}
