// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { LandClaimTableData } from "./../Tables.sol";

interface ILandClaimSystem {
  function claimLand(uint256 nftId) external returns (uint8[] memory cells);

  function upgradeLand(uint256 nftId, uint256 tokenAmount) external returns (uint8[] memory cells);

  function ableClaim(address holder, uint256 nftId) external view returns (bool);

  function getClaimResult(uint256 nftId) external view returns (LandClaimTableData memory item);
}
