// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IFireTokenSystem } from "./IFireTokenSystem.sol";
import { IInitialConfigSystem } from "./IInitialConfigSystem.sol";
import { ILandClaimSystem } from "./ILandClaimSystem.sol";
import { INftSystem } from "./INftSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is IBaseWorld, IFireTokenSystem, IInitialConfigSystem, ILandClaimSystem, INftSystem {

}
